apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      #Fazendo referência direto ao arquivo configmap, importando todas as variáveis.
      envFrom:
        - configMapRef:
            name: db-configmap


# Exemplo de variaveis especificas importada.    

# - env:
#    - name: MYSQL_ROOT_PASSWORD
#        valueFrom:
#          configMapKeyRef:
#           name: db-configmap
#           key: MYSQL_ROOT_PASSWORD

#----------------------------------------#

# Verificar os pods
# $ kubectl get pods

#----------------------------------------#

# Acessar o pod do sistema em modo interativo;
# $ kubectl exec -it db-noticias -- bash

# Acessar o Mysql
# $ mysql -u root -p
# senha: q1w2e3r4 

# Verificar o banco existente
# show databases;
# show use;
# show tables;
# comandos sql.

