apiVersion: v1
kind: ConfigMap
metadata: 
  name: portal-configmap
data: 
  # windows é o IP do SISTEMA http://localhost:30006
  # Linux é o INTERNAL IP do NODE:30006
  IP_SISTEMA: http://192.168.1.106:30006

# Verificar os pods
# $ kubectl get pods

#----------------------------------------#

# Acessar o pod do sistema em modo interativo;
# $ kubectl exec -it portal-noticias -- bash

#Arquivos localizados em /var/www/html/.

#As informações para associar o configmap estão em configuração.php