apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
    - name: sistema-noticias-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: sistema-configmap

# Verificar os pods
# $ kubectl get pods

#----------------------------------------#

# Acessar o pod do sistema em modo interativo;
# $ kubectl exec -it sistema-noticias -- bash

#Arquivos localizados em /var/www/html/.