apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30006
      # O seletor faz referência aoo pod que terá a configuração especificada acima.
  selector:
    app: sistema-noticias
